# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Portfolio

on:
  push:
    branches: [ "master" ]    
jobs:
  uploading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ftp-action
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{secrets.FTP_SERVER}}
        # FTP user
        user: ${{secrets.FTP_USERNAME}}
        # FTP password
        password: ${{secrets.FTP_PASSWORD}}
        # Force SSL encryption
        forceSsl: false
        # Local directory
        localDir: .
        # Remote directory
        remoteDir: .
